jobS/app/urls.py
from django.urls import path
from .import views
urlpatterns = [
    path('login/',views.ulogin,name='login'),
    path('register/',views.register,name='register'),
    path('',views.home,name='home'),
    path('jview/<int:pk>',views.jview,name='jview'),
    path('upload_resume/', views.upload_resume, name='upload_resume'),
    path('apply/<int:pk>', views.apply, name='apply'),
    path('cview/', views.cview, name='cview'),
    path('cjview/<int:pk>', views.cjview, name='cjview'),
    path('logout/', views.uLogout, name='logout'),
    path('create_job/', views.create_job, name='create_job'),
    path('search/', views.search, name='search'),
]

jobS/jobS/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobS/app/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms



# Create your models here.
class Juser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,related_name='customer',null=True,blank=True)
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    employer = models.BooleanField(default=False)

    def __str__(self):
        return self.name
    
class Resume(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100, null=True)
    last_name = models.CharField(max_length=100, null=True)
    linkdean = models.CharField(max_length=100, null=True)
    pdf = models.FileField(upload_to='resumes/')
    upload_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"



class Job(models.Model):
    company = models.ForeignKey(Juser,on_delete=models.CASCADE)
    title = models.CharField(max_length=200,null=True)
    j_description = models.CharField(max_length=1000,null=True)
    skills = models.CharField(max_length=200,null=True)
    offer = models.IntegerField()
    date = models.DateField(auto_now_add=True)
    location = models.CharField(max_length=100,null=True)
    no_of_opening = models.IntegerField(default=1)

    def __str__(self):
        return self.title
    
class Apply(models.Model):
    job = models.ForeignKey(Job,  on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    resume = models.ForeignKey(Resume,on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    

jobS/app/forms.py
from django import forms
from .models import Resume,Job

class ResumeForm(forms.ModelForm):
    class Meta:
        model = Resume
        fields = ['first_name', 'last_name', 'linkdean', 'pdf']

class Cform(forms.ModelForm):
    class Meta:
        model = Job
        fields = ['title', 'j_description', 'skills', 'offer', 'location', 'no_of_opening']

jobS/app/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.models import User
from .models import*
from .forms import ResumeForm,Cform
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q

# Create your views here.
def register(request):
    
    if request.method == "POST":
        uname = request.POST.get('uname')
        email = request.POST.get('email')
        pass1 = request.POST.get('password1')
        pass2 = request.POST.get('password2')
        employer = request.POST.get('option1')
        if pass1!=pass2:
            messages.success(request,'First and second passwords are not same')
            return render(request,'register.html')
        if User.objects.filter(username=uname).exists() or User.objects.filter(email=email).exists():
            messages.success(request,'Username or email already exists')
            return render(request, 'register.html')   

        else:
            my_user=User.objects.create_user(uname,email,pass1)
            my_user.save()
            if employer == 'Yes':
                juser = Juser.objects.create(user=my_user, name=uname, email=email,employer = True)
                juser.save()
            else:
                juser = Juser.objects.create(user=my_user, name=uname, email=email,employer=False)
                juser.save()
                
            #print(uname,email,pass1,pass2)
            return redirect('login')  
    return render(request,'register.html')

def ulogin(request):
    if request.method == "POST":
        uname = request.POST.get('uname')
        password = request.POST.get('password')
        
        user = authenticate(request, username=uname, password=password)
        
        if user is not None:
            login(request, user)
            juser = Juser.objects.get(user = user)
            if juser.employer:
                return redirect('cview')
            try:
                resume = Resume.objects.get(user=user)
                return redirect('home')
            except ObjectDoesNotExist:
                return redirect('upload_resume')
        else:
            messages.error(request, 'Please enter correct username or password')
            return render(request, 'login.html')

    return render(request, 'login.html')

def home(request):
    job = Job.objects.all()
    context = {'jobs':job}
    return render(request,'home.html',context)
def jview(request,pk):
        
        job = Job.objects.get(id=pk)
        
        
        context = {'job':job}
        print(job.id)
        return render(request,'view.html',context)
    
    
def upload_resume(request):
    try:
        if request.method == 'POST':
            form = ResumeForm(request.POST, request.FILES)
            if form.is_valid():
                resume = form.save(commit=False)
                resume.user = request.user  
                resume.save()
                return redirect('home') 
        else:
            form = ResumeForm()
    except:
        messages.success(request,'Something Wents wrong')
        return redirect('home')
    return render(request, 'personal.html', {'form': form})

def create_job(request):
    try:
        if request.method == 'POST':
            form = Cform(request.POST, request.FILES)
            if form.is_valid():
                job = form.save(commit=False)
                juser = Juser.objects.get(user = request.user)
                job.company = juser
                job.save()
                return redirect('cview') 
        else:
            form = Cform()
    except:
        messages.success(request,'Something Wents wrong')
        return redirect('cview')
    return render(request, 'create_job.html', {'form': form})

def apply(request,pk):
    user =  request.user
    job = Job.objects.get(id=pk)
    resume = Resume.objects.get(user = user)
    if Apply.objects.filter(user = user,job=job).exists():
        messages.success(request,"Already Applied")
        return redirect('home')
    else:
        apply= Apply.objects.create(job=job,user=user,resume=resume)
        apply.save()
        messages.success(request,"Applied")
    return render(request,'home.html')

def cview(request):
    user = request.user
    user = Juser.objects.get(user = user)
    if Job.objects.filter(company = user).exists():
        job = Job.objects.filter(company = user)
        print(job)
        context = {'jobs':job}
        return render(request,'cview.html',context)
    else:
        messages.success(request,'No jobs Posted Yet')
    return render(request,'cview.html')

def cjview(request,pk):
    job = Job.objects.get(id=pk)
    apply = Apply.objects.filter(job = job)
    context = {'jobs':job, 'applys':apply}
    return render(request,'cjview.html',context)
def uLogout(request):
    logout(request)
    return redirect('home')

def search(request):
    try:
        if request.method == 'POST':
            querry = request.POST.get('search')
            print(querry)
            job = Job.objects.filter((Q(title__icontains= querry)) | (Q(skills__icontains= querry)))
            if job.exists():
                context ={'jobs':job}
                return render(request,'home.html',context)
            else:
                messages.success(request,'No result Found')
                return redirect('home')
    except:
        messages.success(request,'No result Found')
        return redirect('home')

jobS/app/templates/create_job.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <style>
        :root {
            --color-white: #ffffff;
            --color-light: #f1f5f9;
            --color-black: #121212;
            --color-night: #001632;
        
            --color-red: #f44336;
            --color-blue: #1a73e8;
            --color-gray: #80868b;
            --color-grayish: #dadce0;
        
            --shadow-normal: 0 1px 3px 0 rgba(0, 0, 0, 0.1),
                0 1px 2px 0 rgba(0, 0, 0, 0.06);
            --shadow-medium: 0 4px 6px -1px rgba(0, 0, 0, 0.1),
                0 2px 4px -1px rgba(0, 0, 0, 0.06);
            --shadow-large: 0 10px 15px -3px rgba(0, 0, 0, 0.1),
                0 4px 6px -2px rgba(0, 0, 0, 0.05);
        }
        
        html {
            font-size: 100%;
            font-size-adjust: 100%;
            box-sizing: border-box;
            scroll-behavior: smooth;
        }
        
        *,
        *::before,
        *::after {
            padding: 0;
            margin: 0;
            box-sizing: inherit;
            list-style: none;
            list-style-type: none;
            text-decoration: none;
            -webkit-font-smoothing: antialiased;
            -moz-osx-font-smoothing: grayscale;
            text-rendering: optimizeLegibility;
        }
        
        body {
            font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
            font-size: 1rem;
            font-weight: normal;
            line-height: 1.5;
            color: var(--color-black);
            background: var(--color-light);
        }
        
        a,
        button {
            font-family: inherit;
            font-size: inherit;
            line-height: inherit;
            cursor: pointer;
            border: none;
            outline: none;
            background: none;
            text-decoration: none;
        }
        
        img {
            display: block;
            width: 100%;
            height: auto;
            object-fit: cover;
        }
        
        
        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            max-width: 80rem;
            min-height: 100vh;
            width: 100%;
            padding: 0 2rem;
            margin: 0 auto;
        }
        
        .ion {
            &-logo-apple {
                font-size: 1.65rem;
                line-height: inherit;
                margin-right: 0.5rem;
                color: var(--color-black);
            }
            &-logo-google {
                font-size: 1.65rem;
                line-height: inherit;
                margin-right: 0.5rem;
                color: var(--color-red);
            }
            &-logo-facebook {
                font-size: 1.65rem;
                line-height: inherit;
                margin-right: 0.5rem;
                color: var(--color-blue);
            }
        }
        
        .text {
            font-family: inherit;
            line-height: inherit;
            text-transform: unset;
            text-rendering: optimizeLegibility;
        
            &-large {
                font-size: 2rem;
                font-weight: 600;
                color: var(--color-black);
            }
        
            &-normal {
                font-size: 1rem;
                font-weight: 400;
                color: var(--color-black);
            }
        
            &-links {
                font-size: 1rem;
                font-weight: 400;
                color: var(--color-blue);
        
                &:hover {
                    text-decoration: underline;
                }
            }
        }
        
        
        .main {
            .wrapper {
                max-width: 28rem;
                width: 100%;
                margin: 2rem auto;
                padding: 2rem 2.5rem;
                border: none;
                outline: none;
                border-radius: 0.25rem;
                color: var(--color-black);
                background: var(--color-white);
                box-shadow: var(--shadow-large);
        
                .form {
                    width: 100%;
                    height: auto;
                    margin-top: 2rem;
        
                    .input-control {
                        display: flex;
                        align-items: center;
                        justify-content: space-between;
                        margin-bottom: 1.25rem;
                    }
        
                    .input-field {
                        font-family: inherit;
                        font-size: 1rem;
                        font-weight: 400;
                        line-height: inherit;
                        width: 100%;
                        height: auto;
                        padding: 0.75rem 1.25rem;
                        border: none;
                        outline: none;
                        border-radius: 2rem;
                        color: var(--color-black);
                        background: var(--color-light);
                        text-transform: unset;
                        text-rendering: optimizeLegibility;
                    }
        
                    .input-submit {
                        font-family: inherit;
                        font-size: 1rem;
                        font-weight: 500;
                        line-height: inherit;
                        cursor: pointer;
                        min-width: 40%;
                        height: auto;
                        padding: 0.65rem 1.25rem;
                        border: none;
                        outline: none;
                        border-radius: 2rem;
                        color: var(--color-white);
                        background: var(--color-blue);
                        box-shadow: var(--shadow-medium);
                        text-transform: capitalize;
                        text-rendering: optimizeLegibility;
                    }
                }
        
                .striped {
                    display: flex;
                    flex-direction: row;
                    justify-content: center;
                    align-items: center;
                    margin: 1rem 0;
        
                    &-line {
                        flex: auto;
                        flex-basis: auto;
                        border: none;
                        outline: none;
                        height: 2px;
                        background: var(--color-grayish);
                    }
        
                    &-text {
                        font-family: inherit;
                        font-size: 1rem;
                        font-weight: 500;
                        line-height: inherit;
                        color: var(--color-black);
                        margin: 0 1rem;
                    }
                }
        
                .method {
                    &-control {
                        margin-bottom: 1rem;
                    }
        
                    &-action {
                        font-family: inherit;
                        font-size: 0.95rem;
                        font-weight: 500;
                        line-height: inherit;
                        display: flex;
                        justify-content: center;
                        align-items: center;
                        width: 100%;
                        height: auto;
                        padding: 0.35rem 1.25rem;
                        outline: none;
                        border: 2px solid var(--color-grayish);
                        border-radius: 2rem;
                        color: var(--color-black);
                        background: var(--color-white);
                        text-transform: capitalize;
                        text-rendering: optimizeLegibility;
                        transition: all 0.35s ease;
        
                        &:hover {
                            background: var(--color-light);
                        }
                    }
                }
            }
        }
        
    </style>
</head>
  <main class="main">
	<div class="container">
		<section class="wrapper">
			<div class="heading">
				<h1 class="text text-large">Resume</h1>
				
			</div>
            <form method="post" enctype="multipart/form-data">
                
                {% csrf_token %}
                {% if messages %}
                <div class="pt-3">
                <div class="alert alert-success" role="alert">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
                
                </div>
                </div>
                {% endif %}
                <div class="input-control pt-3">
					
                    <label class = "input-field" for="id_first_name">Title:</label>
                        {{ form.title}}
                        <br>
				</div>
                <div class="input-control pt-3">
					<label class = "input-field" for="id_last_name">Description:</label>
                    {{ form.j_description }}
                    <br>
				</div>
				<div class="input-control pt-3">
					<label class="input-field" for="id_linkdean">Required Skills:</label>
                    {{ form.skills }}
                    <br>
                </div>
                <div class="input-control pt-3">
                    <label class = "input-field" for="id_pdf">Offer:</label>
                    {{ form.offer }}
                    <br>
                </div>
                <div class="input-control pt-3">
                    <label class = "input-field" for="id_pdf">Location:</label>
                    {{ form.location }}
                    <br>
                </div>
                <div class="input-control pt-3">
                    <label class = "input-field" for="id_pdf">NO. of Openings:</label>
                    {{ form.no_of_opening }}
                    <br>
                </div>
                <div class="pt-3">
                    <button type="submit" class="btn btn-primary input-submit ">Create</button>
                </div>
			</form>
			
		</section>
	</div>
</main>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
</body>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
    <!-- First Name -->
    
    
    <!-- Last Name -->
    
    
    <!-- LinkedIn Profile -->
    
</form>

</body>
</html>

jobS/app/templates/main.html
{% load static %}
{% include 'header.html' %}


<body>
<div class='container'>
    
{% block content %}

{% endblock  %}
</div>

</body>
<div class="pt-4" style="
bottom: 0; width:100%;">
{% include 'footer.html' %}
</div>

jobS/app/templates/personal.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <style>
        :root {
            --color-white: #ffffff;
            --color-light: #f1f5f9;
            --color-black: #121212;
            --color-night: #001632;
        
            --color-red: #f44336;
            --color-blue: #1a73e8;
            --color-gray: #80868b;
            --color-grayish: #dadce0;
        
            --shadow-normal: 0 1px 3px 0 rgba(0, 0, 0, 0.1),
                0 1px 2px 0 rgba(0, 0, 0, 0.06);
            --shadow-medium: 0 4px 6px -1px rgba(0, 0, 0, 0.1),
                0 2px 4px -1px rgba(0, 0, 0, 0.06);
            --shadow-large: 0 10px 15px -3px rgba(0, 0, 0, 0.1),
                0 4px 6px -2px rgba(0, 0, 0, 0.05);
        }
        
        html {
            font-size: 100%;
            font-size-adjust: 100%;
            box-sizing: border-box;
            scroll-behavior: smooth;
        }
        
        *,
        *::before,
        *::after {
            padding: 0;
            margin: 0;
            box-sizing: inherit;
            list-style: none;
            list-style-type: none;
            text-decoration: none;
            -webkit-font-smoothing: antialiased;
            -moz-osx-font-smoothing: grayscale;
            text-rendering: optimizeLegibility;
        }
        
        body {
            font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
            font-size: 1rem;
            font-weight: normal;
            line-height: 1.5;
            color: var(--color-black);
            background: var(--color-light);
        }
        
        a,
        button {
            font-family: inherit;
            font-size: inherit;
            line-height: inherit;
            cursor: pointer;
            border: none;
            outline: none;
            background: none;
            text-decoration: none;
        }
        
        img {
            display: block;
            width: 100%;
            height: auto;
            object-fit: cover;
        }
        
        
        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            max-width: 80rem;
            min-height: 100vh;
            width: 100%;
            padding: 0 2rem;
            margin: 0 auto;
        }
        
        .ion {
            &-logo-apple {
                font-size: 1.65rem;
                line-height: inherit;
                margin-right: 0.5rem;
                color: var(--color-black);
            }
            &-logo-google {
                font-size: 1.65rem;
                line-height: inherit;
                margin-right: 0.5rem;
                color: var(--color-red);
            }
            &-logo-facebook {
                font-size: 1.65rem;
                line-height: inherit;
                margin-right: 0.5rem;
                color: var(--color-blue);
            }
        }
        
        .text {
            font-family: inherit;
            line-height: inherit;
            text-transform: unset;
            text-rendering: optimizeLegibility;
        
            &-large {
                font-size: 2rem;
                font-weight: 600;
                color: var(--color-black);
            }
        
            &-normal {
                font-size: 1rem;
                font-weight: 400;
                color: var(--color-black);
            }
        
            &-links {
                font-size: 1rem;
                font-weight: 400;
                color: var(--color-blue);
        
                &:hover {
                    text-decoration: underline;
                }
            }
        }
        
        
        .main {
            .wrapper {
                max-width: 28rem;
                width: 100%;
                margin: 2rem auto;
                padding: 2rem 2.5rem;
                border: none;
                outline: none;
                border-radius: 0.25rem;
                color: var(--color-black);
                background: var(--color-white);
                box-shadow: var(--shadow-large);
        
                .form {
                    width: 100%;
                    height: auto;
                    margin-top: 2rem;
        
                    .input-control {
                        display: flex;
                        align-items: center;
                        justify-content: space-between;
                        margin-bottom: 1.25rem;
                    }
        
                    .input-field {
                        font-family: inherit;
                        font-size: 1rem;
                        font-weight: 400;
                        line-height: inherit;
                        width: 100%;
                        height: auto;
                        padding: 0.75rem 1.25rem;
                        border: none;
                        outline: none;
                        border-radius: 2rem;
                        color: var(--color-black);
                        background: var(--color-light);
                        text-transform: unset;
                        text-rendering: optimizeLegibility;
                    }
        
                    .input-submit {
                        font-family: inherit;
                        font-size: 1rem;
                        font-weight: 500;
                        line-height: inherit;
                        cursor: pointer;
                        min-width: 40%;
                        height: auto;
                        padding: 0.65rem 1.25rem;
                        border: none;
                        outline: none;
                        border-radius: 2rem;
                        color: var(--color-white);
                        background: var(--color-blue);
                        box-shadow: var(--shadow-medium);
                        text-transform: capitalize;
                        text-rendering: optimizeLegibility;
                    }
                }
        
                .striped {
                    display: flex;
                    flex-direction: row;
                    justify-content: center;
                    align-items: center;
                    margin: 1rem 0;
        
                    &-line {
                        flex: auto;
                        flex-basis: auto;
                        border: none;
                        outline: none;
                        height: 2px;
                        background: var(--color-grayish);
                    }
        
                    &-text {
                        font-family: inherit;
                        font-size: 1rem;
                        font-weight: 500;
                        line-height: inherit;
                        color: var(--color-black);
                        margin: 0 1rem;
                    }
                }
        
                .method {
                    &-control {
                        margin-bottom: 1rem;
                    }
        
                    &-action {
                        font-family: inherit;
                        font-size: 0.95rem;
                        font-weight: 500;
                        line-height: inherit;
                        display: flex;
                        justify-content: center;
                        align-items: center;
                        width: 100%;
                        height: auto;
                        padding: 0.35rem 1.25rem;
                        outline: none;
                        border: 2px solid var(--color-grayish);
                        border-radius: 2rem;
                        color: var(--color-black);
                        background: var(--color-white);
                        text-transform: capitalize;
                        text-rendering: optimizeLegibility;
                        transition: all 0.35s ease;
        
                        &:hover {
                            background: var(--color-light);
                        }
                    }
                }
            }
        }
        
    </style>
</head>
  <main class="main">
	<div class="container">
		<section class="wrapper">
			<div class="heading">
				<h1 class="text text-large">Resume</h1>
				
			</div>
            <form method="post" enctype="multipart/form-data">
                
                {% csrf_token %}
                {% if messages %}
                <div class="pt-3">
                <div class="alert alert-success" role="alert">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
                
                </div>
                </div>
                {% endif %}
                <div class="input-control pt-3">
					
                    <label class = "input-field" for="id_first_name">First Name:</label>
                        {{ form.first_name }}
                        <br>
				</div>
                <div class="input-control pt-3">
					<label class = "input-field" for="id_last_name">Last Name:</label>
                    {{ form.last_name }}
                    <br>
				</div>
				<div class="input-control pt-3">
					<label class="input-field" for="id_linkdean">LinkedIn Profile:</label>
                    {{ form.linkdean }}
                    <br>
                </div>
                <div class="input-control pt-3">
                    <label class = "input-field" for="id_pdf">Upload Resume (PDF):</label>
                    {{ form.pdf }}
                    <br>
                </div>
                <div class="pt-3">
                    <button type="submit" class="btn btn-primary input-submit ">Upload Resume</button>
                </div>
			</form>
			
		</section>
	</div>
</main>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
</body>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
    <!-- First Name -->
    
    
    <!-- Last Name -->
    
    
    <!-- LinkedIn Profile -->
    
</form>

</body>
</html>